package com.akamatsu.diseo.pedemeia.Model;

import io.realm.RealmObject;

/**
 * Created by Avell B155 on 27/07/16.
 */
public class Balance extends RealmObject {
    private Float value;
    private Float extra;

    // Standard getters & setters generated by your IDE…
    public Float getValue() { return value; }
    public void   setValue(Float name) { this.value = value; }
    public Float getExtra() { return extra; }
    public void   setExtra(Float extra) { this.extra = extra; }
}