package com.akamatsu.diseo.pedemeia.Model;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;

/**
 * Created by Avell B155 on 12/07/16.
 */
public class Goal extends RealmObject {

    private String name;
    private Float price;
    private Float deadline;

    private Float investedValue;

    @Ignore
    private int id;

    // Standard getters & setters generated by your IDE…
    public String getName() { return name; }
    public void   setName(String name) { this.name = name; }
    public Float getPrice() { return price; }
    public void   setPrice(Float price) { this.price = price; }
    public Float getDeadline() { return deadline; }
    public void   setDeadline(Float deadline) { this.deadline = deadline; }

    public Float getInvestedValue() { return investedValue; }
    public void   setInvestedValue(Float investedValue) { this.investedValue = investedValue; }

    public int    getId() { return id; }
    public void   setId(int id) { this.id = id; }
}
