package com.akamatsu.diseo.pedemeia.Model;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;

/**
 * Created by Avell B155 on 12/07/16.
 */
public class Goal extends RealmObject {

    private String name;
    private String price;
    private String deadline;

    @Ignore
    private int id;

    // Standard getters & setters generated by your IDE…
    public String getName() { return name; }
    public void   setName(String name) { this.name = name; }
    public String getPrice() { return price; }
    public void   setPrice(String price) { this.price = price; }
    public String getDeadline() { return name; }
    public void   setDeadline(String deadline) { this.deadline = deadline; }

    public int    getId() { return id; }
    public void   setId(int id) { this.id = id; }
}
