package com.akamatsu.diseo.pedemeia.Model;

import io.realm.RealmObject;
import io.realm.annotations.Ignore;

/**
 * Created by Avell B155 on 12/07/16.
 */
public class Transaction extends RealmObject {

    private String name;
    private Float value;
    private String deadline;
    private Boolean incoming; //if not = outgoing

    @Ignore
    private int id;

    // Standard getters & setters generated by your IDE…
    public String getName() { return name; }
    public void   setName(String name) { this.name = name; }
    public Float getValue() { return value; }
    public void   setValue(Float value) { this.value = value; }

    public int    getId() { return id; }
    public void   setId(int id) { this.id = id; }
}
